project:
  type: website

website:
  title: "The Visual Analytics"
  navbar:
    left:
      - text: "Hands-On Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "1-Hands_On_Exercise/HandsOnEx1/HandsOnEx1.html"
          - text: "Hands-on Exercise 2"
            href: "1-Hands_On_Exercise/HandsOnEx2/HandsOnEx2.html"
          - text: "Hands-on Exercise 3"
            href: "1-Hands_On_Exercise/HandsOnEx3/HandsOnEx3.html"            
          - text: "Hands-on Exercise 4"
            href: "1-Hands_On_Exercise/HandsOnEx4/HandsOnEx4.html"
          - text: "Hands-on Exercise 5"
            href: "1-Hands_On_Exercise/HandsOnEx5/HandsOnEx5.html"            
          - text: "Hands-on Exercise 6"
            href: "1-Hands_On_Exercise/HandsOnEx6/HandsOnEx6.html"
            
      - text: "In-Class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: "2-In_Class_Exercise/InClassEx1/InClassEx1.html"
          - text: "In-class Exercise 2"
            href: "2-In_Class_Exercise/InClassEx2/InClassEx2.html"
          - text: "In-class Exercise 3"
            href: "2-In_Class_Exercise/InClassEx3/InClassEx3.html"          
          - text: "In-class Exercise 4"
            href: "2-In_Class_Exercise/InClassEx4/InClassEx4.html"          
          
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "3-Take_Home_Exercise/TakeHomeEx1/TakeHomeEx1.html"
          - text: "Take-home Exercise 2"
            href: "3-Take_Home_Exercise/TakeHomeEx02/TakeHomeEx02.html"
          
      - text: "Project"
        menu: 
          - text: "Coming Soon"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

